### ISSUE TITLE
closed issues are not displayed

### ISSUE THREAD

**Issue by bestbean** [matthiasblaesing/netbeans-mantis-integration#26] opened 2015-07-20 10:14 UTC

**Comment by matthiasblaesing** [comment] 2015-07-21 18:16
Thank you for your report. You are right the issue is reproducible and is rooted in the way searching works. Basicly this happens:

1. Mantis is asked to provide all issue headers
2. The query is then matched against the headers
3. For matched headers the id is extracted
4. For all ids the comple issue is fetched

All issue headers is kind of vague in this case, as a default filter is applied and that filter is filled from the configuration:

```php
        /**
         *
         * @global int $g_hide_status_default
         */
        $g_hide_status_default  = CLOSED;
```

See: https://www.mail-archive.com/mantisbt-help@lists.sourceforge.net/msg00593.html

For the future the API was extended and the current beta hold a promising method. Till then please

a) either change the default described above or
b) test with a predefined query on server side - this is a gut feeling but should work.

Please don't close this bug, as this needs to followed up, after mantis 1.3 was released

**Comment by bestbean** [comment] 2015-07-21 18:38
Meanwhile, as described in the provided link:
in config_inc.php: $g_hide_status_default='none;
and ALL issues are displayed.

**Closed** 2017-03-02 20:41 UTC
Labels: upstream
